file4 = {
'1':'<h2> 1. “咏鹅 (YǑNG É)” – AN ODE TO THE GOOSE </h2>',
'2':'<i>“An Ode to the Goose” is a short poem from the Tang Dynasty, and is often the first poem that Chinese children are taught due to its simplicity. </i>',
'3':'It was written during the Tang Dynasty by child prodigy poet 骆宾王 (Luò bīn wáng), who penned this poem when he was only seven years old. 骆宾王 would go on to become one of the most famous poets of the Tang Dynasty, and later served as a secretary of the country government of Chang’an.',
'4':'鹅、鹅、鹅，',
'5':'(é é é)',
'6':'曲项向天歌。',
'7':'(qū xiàng xiàng tiān gē)',
'8':'白毛浮绿水，',
'9':'(bái máo fú lǜ shuǐ)',
'10':'红掌拨清波',
'11':'(hóng zhǎng bō qīng bō)',
'12':'English Translation:',
'13':'Goose, goose, goose,',
'14':'You bend your neck towards the sky and sing.',
'15':'Your white feathers float on the emerald water,',
'16':'Your red feet push the clear waves.',
'17':'<h2>2. “静夜思 (JÌNG YÈ SĪ)” - THOUGHTS IN THE SILENT NIGHT </h2>',
'18':'<i>“Thoughts in the Silent Night” was written by famous Tang Dynasty poet 李白 (Lǐbái). The poem expresses the poet’s loneliness, nostalgia, and homesickness as he gazes at the bright moon. 李白 would go on to create close to 1,000 poems in his lifetime, capturing the political landscape and the natural beauty of China in elegant prose.</i>',
'19':'床前明月光，',
'20':'(Chuáng qián míng yuè guāng,)',
'21':'疑是地上霜。',
'22':'(yí shì dì shàng shuāng.)',
'23':'举头望明月，',
'24':'(Jǔ tóu wàng míng yuè,)',
'25':'低头思故乡。',
'26':'(dī tóu sī gù xiāng.)',
'27':'English Translation:',
'28':'Moonlight reflects off the front of my bed.',
'29':'Could it actually be the frost on the ground?',
'30':'I look up to view the bright moon,',
'31':'And look down to reminisce about my hometown.',
'32':'<h2>3. “悯农 (MǏN NÓNG)” – TOILING FARMERS</h2>',
'33':'<i>“Toiling Farmers” was written by Tang Dynasty poet 李绅 (Lǐ shēn) to reflect the grueling working life of a farmer. The first two lines describe how the farmer toils with the hot noon sun bearing down on him, and he is essentially watering the crops with his sweat. The last two lines relates the farmer’s hard work with the food in people’s bowl, and that every grain of rice comes at the expense of hard labor. </i>',
'34':'Interestingly, in present day, this poem is often used at the dinner table by Chinese parents in order to teach their children about not wasting food.',
'35':'锄禾日当午，',
'36':'(Chú hé rì dāng wǔ,)',
'37':'汗滴禾下土。',
'38':'(hàn dī hé xià tǔ.)',
'39':'谁知盘中餐，',
'40':'(Shuí zhī pán zhōng cān,)',
'41':'粒粒皆辛苦。',
'42':'(lì lì jiē xīn kǔ)',
'43':'English Translation:',
'44':'Farmers weeding at noon,',
'45':'Sweat down the field soon.',
'46':'Who knows food on a tray',
'47':'Thanks to their toiling day?'
}